version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventsProject
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"   # localhost:3307 â†’ container:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  spring-app:
    image: rouaroua/eventsproject:latest
    container_name: spring-app
    depends_on:
      - mysql
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eventsProject
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /events
    command: >
      sh -c "
      until mysqladmin ping -hmysql --silent; do
        echo 'Waiting for MySQL...';
        sleep 5;
      done;
      java -jar app.jar
      "

volumes:
  mysql_data:
